services:
  - type: web
    name: line-lead-qsr-backend
    env: python
    plan: starter
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
    rootDir: backend
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: CORS_ORIGINS
        value: "https://app.linelead.io,https://linelead.io,http://localhost:3000"
      - key: PYTHON_VERSION
        value: "3.11"
    healthCheckPath: "/health"