services:
  - type: web
    name: line-lead-qsr-backend
    env: python
    plan: starter
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: CORS_ORIGINS
        value: "https://line-lead-qsr-assistant.vercel.app,http://localhost:3000"
    healthCheckPath: "/health"